import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#0a0a0a',
  },
  message: {
    textAlign: 'center',
    paddingBottom: 20,
    fontSize: 18,
    color: '#333',
    paddingHorizontal: 30,
  },
  camera: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'space-between',
  },
  header: {
    paddingTop: 60,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
    marginBottom: 8,
  },
  instructionText: {
    fontSize: 16,
    color: '#fff',
    textAlign: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    overflow: 'hidden',
  },
  scanFrame: {
    alignSelf: 'center',
    width: width * 0.7,
    height: width * 0.5,
    borderWidth: 3,
    borderColor: '#00E5FF',
    borderRadius: 20,
    backgroundColor: 'transparent',
  },
  resultContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingVertical: 25,
    paddingHorizontal: 30,
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#00E5FF',
    shadowColor: '#00E5FF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  resultLabel: {
    fontSize: 14,
    color: '#00E5FF',
    marginBottom: 8,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  resultText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 2,
    textAlign: 'center',
  },
  buttonContainer: {
    backgroundColor: 'transparent',
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  scanButton: {
    backgroundColor: '#00E5FF',
    paddingVertical: 16,
    borderRadius: 30,
    shadowColor: '#00E5FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  scanButtonText: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
  },
});
